### ISSUE TITLE
Question on how to pilot tabs

### ISSUE THREAD

**Issue by mbariola** [Antony76/DAKboardExtensions#1]
Hello @Antony76 , just happened to find your project.

I am also trying to use DAKBoard frontend, however, I plan to use the Raspberry Pi's GPIO instead of an Arduino.

I am wondering how will you actually cause the tab change. Are there any command line commands to switch between tabs without causing the screen to flicker / chromium reboot etc? how did you intend to do it?

Many thanks for your answer,

M.

**Comment by mbariola** [comment]
actually, I found a way by using xdotool, tried over ssh:

export DISPLAY=:0.0

xdotool search --onlyvisible --name 'Chromium' windowactivate --sync key --clearmodifiers --window 0 ctrl+3

you may close the "issue" , thanks

**Comment by Antony76** [comment]
Hi @mbariola ,
yes xdotool is the right one. You may consider http://appium.io/ as well.
I am using an Arduino as explained in the main page because the ATmega32U4 serie (i.e. Leonardo) are enumerated as USB HID. Then it is really simple to generate keyboerd key like CTRL-TAB to swith between Chromium tabs.
Cheers,
Antony

**Comment by mbariola** [comment]
Thanks! I'm already into wiringPi so I think I'll try that, but will try an
external controller if I am stuck.
Cheers

Il giorno gio 7 set 2017 alle ore 10:34 Antony Bertin <
notifications@github.com> ha scritto:

**Comment by Antony76** [comment]
Hi @mbariola 
did you managed to flip the tabs using wiringPi + xdotool? what kind of keyboard did you use?
A/

**Comment by mbariola** [comment]
Hello @Antony76, yes, I managed. I am using the default English keyboard and language, and through xdotool send ctrl+1 or ctrl+2 commands to switch to tab 1 or 2.
Cycling was a little trickier but I managed to do so sending ctrl+Prior and ctrl+Next. 

This is one of the command sequences I exec:
export DISPLAY=:0.0; xdotool search --onlyvisible --name 'Chromium' windowactivate --sync key --clearmodifiers --window 0 ctrl+2

Note that the export statement is needed.

**Comment by mbariola** [comment]
Oh if you meant physical keyboard - I just read logic 0 signals on the appropriate GPIO pins which are connected to buttons

**Comment by Antony76** [comment]
Great @mbariola , thank you for your response. Are you going to share your hack on github?
Cheers

**Comment by mbariola** [comment]
Hello @Antony76, hope it works for you too. To be honest I didn't think to,
but I might, even though it's really a very simple recipe it could be of
interest to others too
Cheers
